<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-INQUNRP" name="testingPackage.LoginTest" tests="3" failures="1" timestamp="2021-07-03T20:46:49 EDT" time="122.468" errors="0">
  <testcase name="loginTest" time="43.653" classname="testingPackage.LoginTest"/>
  <testcase name="assertURLTest" time="37.136" classname="testingPackage.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.facebook.com/dev] but found [https://www.facebook.com1/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/dev] but found [https://www.facebook.com1/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testingPackage.LoginTest.assertURLTest(LoginTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- assertURLTest -->
  <testcase name="skiipTitleTest" time="41.679" classname="testingPackage.LoginTest">
    <skipped/>
  </testcase> <!-- skiipTitleTest -->
</testsuite> <!-- testingPackage.LoginTest -->
